# Generated by Django 5.2.11 on 2026-02-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodingStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('leetcode', 'LeetCode'), ('gfg', 'GeeksforGeeks'), ('codechef', 'CodeChef'), ('codeforces', 'Codeforces'), ('hackerrank', 'HackerRank')], max_length=50)),
                ('problems_solved', models.PositiveIntegerField()),
                ('rating', models.CharField(blank=True, max_length=50)),
                ('profile_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['-problems_solved'],
            },
        ),
    ]
